name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Exécuter chaque dimanche à minuit UTC

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run NPM audit
      run: npm audit --production
    
    - name: Run ESLint with security plugin
      run: npx eslint . --ext .js,.jsx
    
    - name: Run Unit Tests
      run: npm test
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'market-tracker'
        path: '.'
        format: 'HTML'
        out: 'reports'
    
    - name: Upload OWASP Dependency Check results
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-reports
        path: reports/
    
    - name: Scan for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
